# Generated by Django 5.2.1 on 2026-05-02 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_column='item_code', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, db_column='item_name', default='', max_length=200)),
                ('price_1', models.DecimalField(db_column='price_a', decimal_places=2, default=0.0, max_digits=10, verbose_name='Price 1')),
                ('price_2', models.DecimalField(db_column='price_b', decimal_places=2, default=0.0, max_digits=10, verbose_name='Price 2')),
                ('price_3', models.DecimalField(db_column='price_c', decimal_places=2, default=0.0, max_digits=10, verbose_name='Price 3')),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_level', models.IntegerField(choices=[(1, 'Price Level 1 (Standard)'), (2, 'Price Level 2 (Discount)'), (3, 'Price Level 3 (Wholesale)')], default=1)),
                ('role', models.CharField(default='Sales', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.URLField(blank=True, default='https://ui-avatars.com/api/?name=User&background=random', max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
