# Generated by Django 5.2.13 on 2026-05-01 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price 3'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_level', models.IntegerField(choices=[(1, 'Price Level 1 (Standard)'), (2, 'Price Level 2 (Discount)'), (3, 'Price Level 3 (Wholesale)')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
