# Generated by Django 5.1.7 on 2026-05-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_hours_logged_userprofile_scans_today_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='scans_today',
            new_name='searches_today',
        ),
    ]
