# Generated by Django 5.1.7 on 2026-05-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('employee_onboarded', 'Employee Onboarded'), ('access_change', 'Access Change'), ('profile_update', 'Profile Update'), ('inventory_audit', 'Inventory Audit'), ('policy_update', 'Policy Update'), ('data_sync', 'Data Sync'), ('employee_approved', 'Employee Approved'), ('employee_rejected', 'Employee Rejected')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
