# Generated by Django 5.2.1 on 2026-05-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_reset_otp_userprofile_reset_otp_expiry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitylog',
            table='av_portal_activity_log',
        ),
        migrations.AlterModelTable(
            name='adminnotification',
            table='av_portal_admin_notification',
        ),
        migrations.AlterModelTable(
            name='fcmtoken',
            table='av_portal_fcm_token',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='av_portal_user_profile',
        ),
    ]
