# Generated by Django 5.1.7 on 2026-06-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_activitylog_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
