# Generated by Django 5.2.1 on 2026-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price_label', models.CharField(blank=True, max_length=100, null=True)),
                ('price_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('price_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('price_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'av_portal_product',
            },
        ),
    ]
