name: Build Flutter APK

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # You can specify a version if needed, otherwise it uses the latest stable
          
      - name: Initialize Flutter Project
        working-directory: ./frontend
        run: |
          flutter create --platforms android .
          # Allow HTTP cleartext traffic for local testing
          sed -i 's/<application/<application android:usesCleartextTraffic="true"/g' android/app/src/main/AndroidManifest.xml
          flutter pub get

      - name: Build APK
        working-directory: ./frontend
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: frontend/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
